import type { Locale } from './site';
export const formText = {
  en: {
    name: 'Full name',
    company: 'Company / Organization',
    contactPerson: 'Contact person',
    email: 'Professional email',
    phone: 'Phone number',
    country: 'Country',
    website: 'Company website',
    industry: 'Industry',
    sector: 'Investment sector',
    opportunity: 'Type of opportunity',
    partnership: 'Partnership type',
    description: 'Project or proposal description',
    attachment: 'Company profile / proposal (optional)',
    fileHelp: 'PDF only, maximum 2 MB. Do not include sensitive financial information.',
    consent: 'I agree to the processing of my inquiry as described in the',
    select: 'Please select',
    submit: 'Submit inquiry',
    submitting: 'Submitting…',
    success: 'Your inquiry has been accepted by our receiving service.',
    reference: 'Reference',
    error: 'We could not accept your inquiry. Please try again later.',
    invalid: 'Please check the highlighted fields.',
    required: 'Please enter a valid value.',
    consentError: 'Your consent is required.',
    fileError: 'Attach a valid PDF no larger than 2 MB.',
    challenge: 'Please complete the security check.',
    expired: 'The security check expired. Please try again.',
    rate: 'Too many requests. Please try again in 15 minutes.',
    sectors: ['Real Estate', 'Hospitality', 'Business Development', 'Other'],
    opportunities: [
      'Joint Venture',
      'Project Development',
      'Strategic Investment',
      'Business Partnership',
      'Other',
    ],
    partners: [
      'Real Estate Development',
      'Hospitality Supply',
      'Manufacturing',
      'Distribution',
      'Regional Business Development',
      'Corporate Collaboration',
      'Other',
    ],
    requiredNote: 'All fields are required unless marked optional.',
    optional: 'optional',
    security: 'Security check',
  },
  ar: {
    name: 'الاسم الكامل',
    company: 'الشركة / المؤسسة',
    contactPerson: 'اسم جهة الاتصال',
    email: 'البريد الإلكتروني المهني',
    phone: 'رقم الهاتف',
    country: 'الدولة',
    website: 'موقع الشركة',
    industry: 'القطاع',
    sector: 'قطاع الاستثمار',
    opportunity: 'نوع الفرصة',
    partnership: 'نوع الشراكة',
    description: 'وصف المشروع أو المقترح',
    attachment: 'ملف الشركة / المقترح (اختياري)',
    fileHelp: 'ملف PDF فقط، بحجم أقصى ٢ ميغابايت. لا تُضمّن معلومات مالية حساسة.',
    consent: 'أوافق على معالجة استفساري وفق ما ورد في',
    select: 'يرجى الاختيار',
    submit: 'إرسال الاستفسار',
    submitting: 'جارٍ الإرسال…',
    success: 'قبلت خدمة الاستقبال استفسارك بنجاح.',
    reference: 'رقم المرجع',
    error: 'تعذّر قبول استفسارك. يرجى المحاولة لاحقاً.',
    invalid: 'يرجى مراجعة الحقول المحددة.',
    required: 'يرجى إدخال قيمة صحيحة.',
    consentError: 'موافقتك مطلوبة.',
    fileError: 'أرفق ملف PDF صالحاً لا يتجاوز ٢ ميغابايت.',
    challenge: 'يرجى إكمال التحقق الأمني.',
    expired: 'انتهت صلاحية التحقق الأمني. يرجى المحاولة مجدداً.',
    rate: 'عدد الطلبات كبير. يرجى المحاولة بعد ١٥ دقيقة.',
    sectors: ['العقارات', 'الضيافة', 'تطوير الأعمال', 'أخرى'],
    opportunities: ['مشروع مشترك', 'تطوير مشروع', 'استثمار استراتيجي', 'شراكة أعمال', 'أخرى'],
    partners: [
      'التطوير العقاري',
      'توريد مستلزمات الضيافة',
      'التصنيع',
      'التوزيع',
      'تطوير الأعمال الإقليمي',
      'التعاون المؤسسي',
      'أخرى',
    ],
    requiredNote: 'جميع الحقول مطلوبة ما لم يُذكر أنها اختيارية.',
    optional: 'اختياري',
    security: 'التحقق الأمني',
  },
  tr: {
    name: 'Ad soyad',
    company: 'Şirket / Kuruluş',
    contactPerson: 'İlgili kişi',
    email: 'İş e-postası',
    phone: 'Telefon numarası',
    country: 'Ülke',
    website: 'Şirket web sitesi',
    industry: 'Sektör',
    sector: 'Yatırım sektörü',
    opportunity: 'Fırsat türü',
    partnership: 'Ortaklık türü',
    description: 'Proje veya öneri açıklaması',
    attachment: 'Şirket profili / öneri (isteğe bağlı)',
    fileHelp: 'Yalnızca PDF, en fazla 2 MB. Hassas finansal bilgiler eklemeyin.',
    consent: 'Talebimin şu metinde açıklandığı şekilde işlenmesini kabul ediyorum:',
    select: 'Lütfen seçin',
    submit: 'Talebi gönder',
    submitting: 'Gönderiliyor…',
    success: 'Talebiniz alım hizmetimiz tarafından kabul edildi.',
    reference: 'Referans',
    error: 'Talebinizi kabul edemedik. Lütfen daha sonra tekrar deneyin.',
    invalid: 'Lütfen işaretli alanları kontrol edin.',
    required: 'Lütfen geçerli bir değer girin.',
    consentError: 'Onayınız gereklidir.',
    fileError: 'En fazla 2 MB boyutunda geçerli bir PDF ekleyin.',
    challenge: 'Lütfen güvenlik kontrolünü tamamlayın.',
    expired: 'Güvenlik kontrolünün süresi doldu. Tekrar deneyin.',
    rate: 'Çok fazla istek gönderildi. 15 dakika sonra tekrar deneyin.',
    sectors: ['Gayrimenkul', 'Konaklama', 'İş Geliştirme', 'Diğer'],
    opportunities: [
      'Ortak Girişim',
      'Proje Geliştirme',
      'Stratejik Yatırım',
      'İş Ortaklığı',
      'Diğer',
    ],
    partners: [
      'Gayrimenkul Geliştirme',
      'Konaklama Tedariki',
      'Üretim',
      'Dağıtım',
      'Bölgesel İş Geliştirme',
      'Kurumsal İş Birliği',
      'Diğer',
    ],
    requiredNote: 'İsteğe bağlı olarak belirtilmeyen tüm alanlar zorunludur.',
    optional: 'isteğe bağlı',
    security: 'Güvenlik kontrolü',
  },
};
export const getFormText = (locale: Locale) => formText[locale];
