import type { Locale } from './site';
export const formText = {
  en: {
    name: 'Full name',
    email: 'Email address',
    emailError: 'Enter a valid email address, for example name@company.com.',
    marketing:
      'I agree to receive news and updates from BYHADARA Group and its companies by email. I can unsubscribe at any time.',
    company: 'Company name',
    phone: 'Phone number',
    countryCode: 'Country code',
    popular: 'Popular',
    allCountries: 'All countries',
    website: 'Company website',
    websiteHint: 'If you have a company, add the link to its website.',
    message: 'Your request',
    optional: 'optional',
    requiredNote: 'All fields are required unless marked optional.',
    submit: 'Send request',
    submitting: 'Sending…',
    error: 'We could not send your request. Please try again, or email us at',
    invalid: 'Please check the highlighted fields.',
    required: 'Please enter a valid value.',
    phoneError: 'Choose the country code and enter a valid phone number without it.',
    websiteError: 'Enter a valid website address, for example www.company.com.',
    messageError: 'Please describe your request (at least 10 characters).',
    rate: 'Too many requests. Please try again in 15 minutes.',
    privacyNote:
      'By sending this form, you agree to the handling of your details as described in our',
  },
  ar: {
    name: 'الاسم الكامل',
    email: 'البريد الإلكتروني',
    emailError: 'أدخل بريداً إلكترونياً صحيحاً، مثل name@company.com.',
    marketing:
      'أوافق على تلقي أخبار ومستجدات مجموعة باي حضارة وشركاتها عبر البريد الإلكتروني، ويمكنني إلغاء الاشتراك في أي وقت.',
    company: 'اسم الشركة',
    phone: 'رقم الهاتف',
    countryCode: 'رمز الدولة',
    popular: 'الأكثر استخداماً',
    allCountries: 'جميع الدول',
    website: 'الموقع الإلكتروني للشركة',
    websiteHint: 'إن كانت لديكم شركة، أضيفوا رابط موقعها الإلكتروني.',
    message: 'الطلب',
    optional: 'اختياري',
    requiredNote: 'جميع الحقول مطلوبة ما لم يُذكر أنها اختيارية.',
    submit: 'إرسال الطلب',
    submitting: 'جارٍ الإرسال…',
    error: 'تعذّر إرسال طلبكم. يُرجى المحاولة مرة أخرى أو مراسلتنا على',
    invalid: 'يرجى مراجعة الحقول المحددة.',
    required: 'يرجى إدخال قيمة صحيحة.',
    phoneError: 'اختاروا رمز الدولة وأدخلوا رقم هاتف صحيحاً بدون الرمز.',
    websiteError: 'أدخلوا رابط موقع صحيحاً، مثل www.company.com.',
    messageError: 'يرجى كتابة طلبكم (10 أحرف على الأقل).',
    rate: 'طلبات كثيرة. يرجى المحاولة بعد ١٥ دقيقة.',
    privacyNote: 'بإرسال هذا النموذج، توافقون على التعامل مع بياناتكم كما هو موضح في',
  },
  tr: {
    name: 'Ad soyad',
    email: 'E-posta adresi',
    emailError: 'Geçerli bir e-posta adresi girin, örneğin ad@sirket.com.',
    marketing:
      'BYHADARA Group ve şirketlerinden e-posta ile haber ve duyurular almayı kabul ediyorum. Dilediğim zaman abonelikten çıkabilirim.',
    company: 'Şirket adı',
    phone: 'Telefon numarası',
    countryCode: 'Ülke kodu',
    popular: 'Sık kullanılanlar',
    allCountries: 'Tüm ülkeler',
    website: 'Şirket web sitesi',
    websiteHint: 'Bir şirketiniz varsa web sitesinin bağlantısını ekleyin.',
    message: 'Talebiniz',
    optional: 'isteğe bağlı',
    requiredNote: 'İsteğe bağlı olarak belirtilmeyen tüm alanlar zorunludur.',
    submit: 'Talebi gönder',
    submitting: 'Gönderiliyor…',
    error: 'Talebiniz gönderilemedi. Lütfen tekrar deneyin veya bize şu adresten yazın:',
    invalid: 'Lütfen işaretli alanları kontrol edin.',
    required: 'Lütfen geçerli bir değer girin.',
    phoneError: 'Ülke kodunu seçin ve numarayı kod olmadan geçerli biçimde girin.',
    websiteError: 'Geçerli bir web adresi girin, örneğin www.sirket.com.',
    messageError: 'Lütfen talebinizi yazın (en az 10 karakter).',
    rate: 'Çok fazla istek. Lütfen 15 dakika sonra tekrar deneyin.',
    privacyNote:
      'Bu formu göndererek bilgilerinizin şu metinde açıklandığı şekilde işlenmesini kabul edersiniz:',
  },
};
export type FormText = (typeof formText)['en'];
export const getFormText = (locale: Locale): FormText => formText[locale];
